---
- hosts: all
  become: true
  tasks:
    - name: Update the repository cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install only security updates
      apt:
        upgrade: 'dist'
        update_cache: yes
        force_apt_get: yes
        default_release: "{{ ansible_distribution_release }}-security"